//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biciklino
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delovi
    {
        public int id { get; set; }
        public string Deo { get; set; }
    }
}
