//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biciklino
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novi_Deo
    {
        public int id { get; set; }
        public string NazivOglasa { get; set; }
        public int VrstaDelaID { get; set; }
        public string OpisOglasa { get; set; }
        public string Proizvodjac { get; set; }
    }
}
